// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn0nF8bR16M-XofPG8MD_ypQgB3jKcqqs',
    appId: '1:257686648189:web:2f77c8d2e3dcf6b41f8814',
    messagingSenderId: '257686648189',
    projectId: 'color-tap-game-sk2026',
    authDomain: 'color-tap-game-sk2026.firebaseapp.com',
    storageBucket: 'color-tap-game-sk2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9-PUzaW8oae-Iba3I_aUEOAlRIwZM6Y',
    appId: '1:257686648189:android:ffcbf5b3fa52b9281f8814',
    messagingSenderId: '257686648189',
    projectId: 'color-tap-game-sk2026',
    storageBucket: 'color-tap-game-sk2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHDNuIT85Q-Y7aQxPhvZSmuBR2ej1wfs',
    appId: '1:257686648189:ios:b2c05d98b89a60581f8814',
    messagingSenderId: '257686648189',
    projectId: 'color-tap-game-sk2026',
    storageBucket: 'color-tap-game-sk2026.firebasestorage.app',
    iosBundleId: 'com.example.colorTapGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHDNuIT85Q-Y7aQxPhvZSmuBR2ej1wfs',
    appId: '1:257686648189:ios:b2c05d98b89a60581f8814',
    messagingSenderId: '257686648189',
    projectId: 'color-tap-game-sk2026',
    storageBucket: 'color-tap-game-sk2026.firebasestorage.app',
    iosBundleId: 'com.example.colorTapGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn0nF8bR16M-XofPG8MD_ypQgB3jKcqqs',
    appId: '1:257686648189:web:d048a2d4809909351f8814',
    messagingSenderId: '257686648189',
    projectId: 'color-tap-game-sk2026',
    authDomain: 'color-tap-game-sk2026.firebaseapp.com',
    storageBucket: 'color-tap-game-sk2026.firebasestorage.app',
  );
}
